kind = "mobile"
previewPath = "/"
title = "My Push Ups"
version = "1.0.0"
id = "artifacts/my-push-ups"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 24245

[services.development]
run = "pnpm --filter @workspace/my-push-ups run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/my-push-ups", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/my-push-ups", "run", "serve" ]

[services.env]
PORT = "24245"
BASE_PATH = "/"
